Traceback (most recent call last):
  File "/glade/u/home/gwallach/.conda/envs/goes16/lib/python3.7/site-packages/dask-2.9.2-py3.7.egg/dask/distributed.py", line 3, in <module>
    from distributed import *
ModuleNotFoundError: No module named 'distributed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "goes16_deep_learning_benchmark_64.py", line 10, in <module>
    from goes16ci.data import load_data_serial
  File "/glade/u/home/gwallach/goes16ci/goes16ci/data.py", line 6, in <module>
    from dask.distributed import LocalCluster, Client, wait
  File "/glade/u/home/gwallach/.conda/envs/goes16/lib/python3.7/site-packages/dask-2.9.2-py3.7.egg/dask/distributed.py", line 11, in <module>
    raise ImportError(msg)
ImportError: Dask's distributed scheduler is not installed.

Please either conda or pip install dask distributed:

  conda install dask distributed          # either conda install
  pip install dask distributed --upgrade  # or pip install
